name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      matrix:
        board: [adv360_left, adv360_right]
    name: Build (${{ matrix.board }})
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-modules-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: West Build (${{ matrix.board }})
        run: west build -s zmk/app -b ${{ matrix.board }} -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Upload Firmware (${{ matrix.board }})
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}
          path: build/zephyr/*.uf2
          retention-days: 7
