name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-modules-${{ hashFiles('config/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-modules-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export
      - name: Build (Advantage360 Left)
        run: west build -s zmk/app -b advantange360_left -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Advantage360 Left Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-left
          path: build/zephyr/*.uf2
          retention-days: 7
      - name: Clear Build Directory
        run: rm -rf build
      - name: Build (Advantage360 Right)
        run: west build -s zmk/app -b advantange360_right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Advantage360 Right Artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-right
          path: build/zephyr/*.uf2
          retention-days: 7
